### ISSUE TITLE
Calling RPC with Receivers.All on server does not call it on server

### ISSUE THREAD

**Issue by mcguinnessdr** [BeardedManStudios/ForgeNetworkingRemastered#37] opened 2017-07-26 23:08 UTC
### Version Number and Operating System(s)
Latest Develop branch, commit cad82c4726ced541b2e40f26f8d20db205a4e744
Unity 2017.1.0f3
Windows 10

### Expected behavior
RPC should be called on server, as well as clients.

### Actual behavior
RPC is only called on clients.

### Steps to reproduce
Call `networkObject.SendRpc(RPC_NAME, Receivers.All)` on server.  Clients will receive RPC, but server will not.
You can workaround this by calling `if (NetworkManager.Instance.IsServer) networkObject.SendRpc(NetworkManager.Instance.Networker.Me, RPC_NAME);`

**Comment by mcguinnessdr** [comment] 2017-08-01 01:00
I've narrowed this down a bit.  I am calling the RPC immediately after instantiating the object, or in `networkObject.networkStarted`.  Calling a non-targeted RPC in either of these places will fail, but calling a targeted RPC will succeed.  I'm going to look at how these two cases are handled differently and see if I can find a fix.

**Comment by baflink** [comment] 2017-08-02 17:54
Issue creator has confirmed that this issue is resolved if the RPC is called inside of `NetworkStart` after creation (which should be intended behavior). This is resolved by issue creators pull request:  [](https://github.com/BeardedManStudios/ForgeNetworkingRemastered/pull/46)

**Closed by baflink** 2017-08-02 17:54 UTC
Labels: bug
