### ISSUE TITLE
UDP LAN Discovery fails on OSX

### ISSUE THREAD

**Issue by TheSeanLavery** [BeardedManStudios/ForgeNetworkingRemastered#265] opened 2019-04-24 23:45 UTC
EDIT: It works in Unity 2018. Seems to be related to the mono version of Unity 2017

### Version Number and Operating System(s):
Current Master and DEV. OSX

Edit: Unity version is 2017 LTS
API compatibility is Mono 2.0 Subset

### Expected behavior:
Tick "Get Local Network Connections" in MultiplayerMenu.unity
Build and host server.
Run game in unity editor.
See IP address of discovered host printed into console

### Actual behavior:
No IP address is printed

### Steps to reproduce:
New unity project with forge, tick "Get Local Network Connections"

#### [Optional] Discord Username:
AttackingHobo

**Comment by phalasz** [comment] 2019-04-25 08:40
Interesting as I don't have that issue. I am working on upgrading the multiplayer menu to automatically list local games and potentially master server games in a list.

Are you running both the client and host on OS X?

**Comment by AttackingHobo** [comment] 2019-04-25 21:41
Here is a fix with platform dependent compilation. Don't know if these changes will break under specific conditions. So someone might want to take a look at this, and see if this is good enough, or if there is a better solution.

https://hastebin.com/kitogigata.cs

**Comment by phalasz** [comment] 2019-04-25 23:17
Note: @AttackingHobo confirmed on discord that Unity 2018 does not have the same issue.

It seems to be a problem with the version of mono shipped with earlier versions of Unity.

**Comment by phalasz** [comment] 2019-04-28 11:39
Issue introduced by PR #227

**Comment by SixWays** [comment] 2019-10-04 16:22
LAN discovery also seems to fail on Android, on Unity 2018. I've not been able to test with the commit prior to PR #227 being merged to see if it was working before that.

**Comment by XeviaN360** [comment] 2019-11-01 10:44
> LAN discovery also seems to fail on Android, on Unity 2018. I've not been able to test with the commit prior to PR #227 being merged to see if it was working before that.

I tested it on some android devices, with Unity 2019.2.10f1. The build is failing on some devices (Oculus Quest) and is working on others (Galaxy Note 8 for example). Problem is the NetworkInterface.GetAllNetworkInterfaces() throw an exception: "Unable to find libc".

**Comment by phalasz** [comment] 2019-11-01 11:09
For Android issues please see PR #304

**Comment by phalasz** [comment] 2020-08-10 22:56
2017 LTS is soon end of life.

**Closed by phalasz** 2020-08-10 22:56 UTC
Labels: bug
