### ISSUE TITLE
UDPServer Deadlock Or Socket blocking phenomenon

### ISSUE THREAD

**Issue by ihaiucom** [BeardedManStudios/ForgeNetworkingRemastered#138] opened 2018-03-23 07:32 UTC
### Steps to reproduce:
2 clients to connect to the server
It is normal at this time

When B Client Closes
At this point the A client sends messages to all players again and it is reliable
There will be server messaging jams

**Comment by mcguinnessdr** [comment] 2018-09-30 20:11
Closing due to vagueness and inability to reproducibility.

**Closed by mcguinnessdr** 2018-09-30 20:11 UTC
