### ISSUE TITLE
, Decimal symbol breaks interpolation field

### ISSUE THREAD

**Issue by Hoijima** [BeardedManStudios/ForgeNetworkingRemastered#209] opened 2018-12-18 12:44 UTC
### Version Number and Operating System(s):
09.12.18
Windows 10

### Expected behavior:
Activate interpolation and set it's value 0,1
https://i.imgur.com/Pz1a0Uf.png
### Actual behavior:
param is inactive or set to number after the delimiter
https://i.imgur.com/O4m7ia5.png

### Steps to reproduce:
set the system Decimal symbol to ,
log out - log in
try to set a value to a float using 0,15 as an example
save& compile
view the broken result

#### [Optional] Discord Username:
Lavarius

**Comment by WhelanB** [comment] 2019-01-02 16:48
What language/region is your device set to?

After saving and compiling your object, what values are contained in the [GeneratedInterpol] attribute in the generated networkobject class?

**Comment by Hoijima** [comment] 2019-01-03 19:05
Ru/Ru

Same as the result contained in the second screenshot.

**Comment by WhelanB** [comment] 2019-01-03 21:45
Could you post the actual values contained in the [GeneratedInterpol] attribute within the generated networkobject class (the entire line) or even just pastebin the entire class?

I haven't been able to reproduce this on my own system yet through the network wizard. The issue is consistent with the interpolation values being stored comma-delimited in the [GeneratedInterpol] attribute within the generated class, thus resulting in "0,15" being considered as two separate fields, "0" and "15". This causes the first field to be disabled and the second field to take on a value of 15. 

In theory this should have been fixed with the use of InvariantCulture when the object is compiled, are you using the latest nightly build/have you tried compiling Forge from the repo?

**Comment by WhelanB** [comment] 2019-01-11 22:36
duplicate of #196

**Comment by phalasz** [comment] 2019-04-17 09:15
@Hoijima is this still an issue?

**Comment by phalasz** [comment] 2019-04-28 11:35
No activity on the issue for a long time. Closing. Please let open a new issue if this is still a problem.

**Closed by phalasz** 2019-04-28 11:35 UTC
Labels: duplicate
